{
  "props": [],
  "components": {
    "timer": {
      "type": "script\\TimerScript",
      "x": 384,
      "y": 128,
      "props": {
        "interval": "1000",
        "repeatable": "1",
        "autoStart": "1"
      }
    },
    "ini": {
      "type": "script\\storage\\IniStorage",
      "x": 336,
      "y": 128,
      "props": {
        "path": "config.ini",
        "autoSave": "1",
        "multiLineValues": "1"
      }
    }
  }
}